  name: master
  on:
    push:
      branches:
        - master
        - dev
  jobs:
    push-to-repo:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.8', '3.9', '3.10', '3.11']
      steps:
        - uses: actions/checkout@v3
        - name: Setup Python ${{matrix.python-version}}
          uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip setuptools
            pip install filestore[s3]
            pip install -r requirements.txt
            mkdir -p ./tests/test_data
        - name: Run Tests
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
            AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          run: pytest tests